### ISSUE TITLE
Scripts location on Mac

### ISSUE THREAD

**Issue by cardboardchris** [bdsowers/InDesign_SupportScripts#1]
At least in InDesign 2020, there is another directory inside Scripts, called Scripts Panel. It seems like these scripts need to be installed there to show up in the User folder in the Scripts UI panel.

**Comment by bdsowers** [comment]
Yup, that's true. The readme mentions that folder for Windows, would assume it's the same on Mac.

**Comment by bdsowers** [comment]
Updated the readme to be clearer about the Scripts Panel folder.

**Comment by cardboardchris** [comment]
Oh I see. It doesn't go directly there when using "show in finder".
